# Generated by Django 3.2.6 on 2021-08-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
