# Generated by Django 3.2.6 on 2021-08-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedit_app', '0002_auto_20210829_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='telephone',
            new_name='phone',
        ),
    ]
