# Generated by Django 3.2.6 on 2021-08-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedit_app', '0003_rename_telephone_myuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('visibility', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='picture',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='myuser',
            name='personalData',
            field=models.ManyToManyField(blank=True, to='linkedit_app.PersonalData'),
        ),
    ]
