# Generated by Django 3.2.6 on 2021-09-15 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedit_app', '0004_friendshiplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobproposal',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
