# Generated by Django 3.2.6 on 2021-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedit_app', '0005_auto_20210831_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
