# Generated by Django 3.2.6 on 2021-09-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedit_app', '0007_auto_20210831_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
