# Generated by Django 3.2.6 on 2021-09-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedit_app', '0008_auto_20210901_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeinteraction',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='author',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='content',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='personalData',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='LikeInteraction',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
