# Generated by Django 3.2.6 on 2021-09-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedit_app', '0009_auto_20210910_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='personal_data',
            field=models.ManyToManyField(blank=True, to='linkedit_app.PersonalData'),
        ),
    ]
